/**
 * Deterministic synthetic market for the simulation cockpit.
 *
 * SIMULATION ONLY. These prices are generated by an integer hash of a tick
 * index. They are not a feed, not a quote, and not a price from any venue.
 * Nothing in this file performs I/O of any kind — no network, no RPC, no file.
 *
 * Determinism matters for two reasons:
 *
 *  1. A reviewer can replay a session and get the same numbers, so a decision
 *     shown in the cockpit can be explained after the fact.
 *  2. Tests can assert on behaviour without depending on wall-clock time or a
 *     random seed that changes every run.
 *
 * The walk is bounded on purpose: cumulative drift is clamped to ±9%, so a
 * long-running demo never runs away to a silly price.
 */

import { Money } from "../core/money.js";

export type MarketSymbol = "BTC" | "ETH" | "SOL";

export const MARKET_SYMBOLS: readonly MarketSymbol[] = ["BTC", "ETH", "SOL"] as const;

export interface MarketQuote {
  symbol: MarketSymbol;
  /** micro-USDC per whole token. */
  priceMicros: bigint;
  /** Human form, for display only. */
  priceUsdc: string;
  /** Change against the previous tick, in bps. 0 on tick 0. */
  changeBps: number;
}

/** Base levels for the fake book. Chosen only for realistic-looking digits. */
const BASE_PRICE_MICROS: Record<MarketSymbol, bigint> = {
  BTC: 65_000_000_000n, // 65,000 USDC
  ETH: 3_200_000_000n, // 3,200 USDC
  SOL: 145_000_000n, // 145 USDC
};

/** Per-tick step, in bps. */
const STEP_BPS = 70;
/** Cumulative drift clamp, in bps (±9%). */
const DRIFT_CAP_BPS = 900;

/** FNV-1a, 32-bit. Stable across platforms and Node versions. */
export function hash32(input: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

/** Deterministic value in [-1, 1] for a key. */
export function unitNoise(key: string): number {
  return (hash32(key) / 0xffffffff) * 2 - 1;
}

/** Deterministic index in [0, length). */
export function pickIndex(key: string, length: number): number {
  if (length <= 0) return 0;
  return hash32(key) % length;
}

/**
 * Cumulative drift of a symbol after `tick` steps, in bps.
 *
 * Recomputed from tick 0 every call rather than mutated, so the value at a
 * tick is a pure function of the tick — no hidden process state.
 */
export function cumulativeBps(symbol: MarketSymbol, tick: number): number {
  let sum = 0;
  for (let i = 1; i <= tick; i++) {
    const n = unitNoise(`${symbol}/${i}`);
    const step = n === 0 ? 1 : Math.sign(n) * Math.max(1, Math.round(Math.abs(n) * STEP_BPS));
    sum += step;
    if (sum > DRIFT_CAP_BPS) sum = DRIFT_CAP_BPS;
    else if (sum < -DRIFT_CAP_BPS) sum = -DRIFT_CAP_BPS;
  }
  return sum;
}

/** Synthetic price of a symbol at a tick, in micro-USDC. Pure function. */
export function syntheticPriceMicros(symbol: MarketSymbol, tick: number): bigint {
  const base = BASE_PRICE_MICROS[symbol];
  return (base * BigInt(10_000 + cumulativeBps(symbol, tick))) / 10_000n;
}

function quoteAt(symbol: MarketSymbol, tick: number): MarketQuote {
  const priceMicros = syntheticPriceMicros(symbol, tick);
  const previous = tick > 0 ? syntheticPriceMicros(symbol, tick - 1) : priceMicros;
  const changeBps = previous === 0n ? 0 : Number(((priceMicros - previous) * 10_000n) / previous);
  return {
    symbol,
    priceMicros,
    priceUsdc: fmtUsdc(priceMicros),
    changeBps,
  };
}

/**
 * Display-only USDC formatter.
 *
 * `Money.format()` is the arithmetic path's formatter and is not used here
 * because P&L can be negative and this needs a clean "-12.34" for the UI.
 * Never used for a limit check — see src/core/money.ts.
 */
export function fmtUsdc(micros: bigint): string {
  const negative = micros < 0n;
  const abs = negative ? -micros : micros;
  const whole = abs / 1_000_000n;
  const frac = (abs % 1_000_000n).toString().padStart(6, "0").replace(/0+$/, "");
  return `${negative ? "-" : ""}${whole}${frac ? `.${frac}` : ""}`;
}

/** The shared, deterministic fake book. One instance per cockpit process. */
export class SyntheticMarket {
  private tickIndex = 0;

  get tick(): number {
    return this.tickIndex;
  }

  price(symbol: MarketSymbol, tick = this.tickIndex): bigint {
    return syntheticPriceMicros(symbol, tick);
  }

  quote(symbol: MarketSymbol): MarketQuote {
    return quoteAt(symbol, this.tickIndex);
  }

  quotes(): MarketQuote[] {
    return MARKET_SYMBOLS.map((s) => quoteAt(s, this.tickIndex));
  }

  /** Advance one tick. Returns the new tick index. */
  step(): number {
    this.tickIndex += 1;
    return this.tickIndex;
  }

  /** Rewind to tick 0. Used by `reset`. */
  reset(): void {
    this.tickIndex = 0;
  }
}
